services:
  accounts:
    image: "romasko/accounts:s4" #You need to change this to your Docker Hub username
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network
  loans:
    image: "romasko/loans:s4" #You need to change this to your Docker Hub username
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network
  cards:
    image: "romasko/cards:s4" #You need to change this to your Docker Hub username
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network
networks:
  banking-network:
    driver: "bridge"