build:
  version: "3.0"

accounts:
  message: "Welcome to bank accounts related local APIs "
  contactDetails:
    name: "Onur Can - Developer"
    email: "example1@example.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
