build:
  version: "1.0"

cards:
  message: "Welcome to bank cards related prod APIs "
  contactDetails:
    name: "10UR - Product Owner"
    email: "example5@example.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721