build:
  version: "2.0"

cards:
  message: "Welcome to bank cards related QA APIs "
  contactDetails:
    name: "10ur Can - QA Lead"
    email: "example6@example.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267